-- CREATE TABLE COURSE(
-- 	ID SERIAL PRIMARY KEY,
-- 	NAME VARCHAR(20)
-- );

-- INSERT INTO COURSE(
-- 	NAME
-- ) VALUES
-- ('PYTHON'),
-- ('MATH'),
-- ('ART');


-- CREATE TABLE STUDENTCOURSE(
-- 	--ID SERIAL PRIMARY KEY,
-- 	STUDENT_ID INT REFERENCES STUDENT(ID),
-- 	COURSE_ID INT REFERENCES COURSE(ID),
-- 	PRIMARY KEY(STUDENT_ID, COURSE_ID)
-- );

-- INSERT INTO STUDENTCOURSE VALUES
-- (10, 1),
-- (8, 1),
-- (15, 2);