-- SELECT *
-- FROM STUDENTCOURSE
-- 	JOIN STUDENT ON STUDENTCOURSE.STUDENT_ID = STUDENT.ID
-- 	JOIN COURSE ON STUDENTCOURSE.COURSE_ID = COURSE.ID


-- ALTER TABLE DOCTOR
-- ADD COLUMN PREMIUM TYPE INT DEFAULT 10

ALTER TABLE WARD
ADD COLUMN DEPERMENT_ID INT REFERENCES DEPARTMENT(ID);

UPDATE WARD
SET DEPERMENT_ID = 1
WHEN ID % 2 = 0;

UPDATE WARD
SET DEPERMENT_ID = 2
WHEN ID % 2 = 1;

UPDATE WARD
SET DEPERMENT_ID = BUILDING
	