-- SELECT *
-- FROM STUDENTCOURSE
-- 	JOIN STUDENT ON STUDENTCOURSE.STUDENT_ID = STUDENT.ID
-- 	JOIN COURSE ON STUDENTCOURSE.COURSE_ID = COURSE.ID


ALTER TABLE DOCTOR
ADD COLUMN PREMIUM TYPE INT DEFAULT 10
	

	